# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0003_remove_users_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onumber', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=50)),
                ('repos', models.CharField(max_length=50)),
                ('transport', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=50)),
                ('note', models.CharField(max_length=128)),
                ('pubtime', models.DateTimeField(auto_now_add=True)),
                ('verify_status', models.IntegerField(default=1)),
                ('send_status', models.IntegerField(default=1)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Users')),
            ],
        ),
    ]
