# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-24 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0005_auto_20160824_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='note',
            field=models.CharField(default='', max_length=128),
        ),
    ]
