# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-28 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0007_auto_20160824_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdersInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentnumber', models.CharField(max_length=50)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('deliverman', models.CharField(max_length=50)),
                ('deleverltd', models.CharField(max_length=50)),
                ('delivernumber', models.CharField(max_length=50)),
                ('verify', models.IntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Orders')),
            ],
        ),
    ]
