# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0008_ordersinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersinfo',
            name='send_date',
            field=models.CharField(max_length=50),
        ),
    ]
