# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0009_auto_20160829_2321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersinfo',
            old_name='deleverltd',
            new_name='deliverltd',
        ),
    ]
