# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 02:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0010_auto_20160829_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='confirm',
            field=models.IntegerField(default=1),
        ),
    ]
