# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-30 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0011_orders_confirm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(max_length=50)),
                ('client_name', models.CharField(max_length=50)),
                ('identity_type', models.CharField(max_length=50)),
                ('identity_nu', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=128)),
                ('mobile', models.CharField(default=None, max_length=50)),
                ('phone', models.CharField(default=None, max_length=50)),
                ('email', models.CharField(default=None, max_length=50)),
                ('fax', models.CharField(default=None, max_length=50)),
                ('urgent_name', models.CharField(default=None, max_length=50)),
                ('urgent_phone', models.CharField(default=None, max_length=50)),
                ('urgent_mobile', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Safe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('car_type', models.CharField(max_length=50)),
                ('equip_name', models.CharField(max_length=50)),
                ('car_name', models.CharField(max_length=50)),
                ('buycar_date', models.CharField(max_length=50)),
                ('safe_date', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('vin', models.CharField(max_length=128)),
                ('sale_man', models.CharField(max_length=50)),
                ('buy_type', models.CharField(max_length=50)),
                ('first_benefit', models.CharField(max_length=50)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Clients')),
            ],
        ),
    ]
