# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-31 02:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0012_clients_safe'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='files',
            field=models.CharField(default=None, max_length=128),
        ),
    ]
