# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 14:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0014_auto_20160831_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
