# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-01 14:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0015_auto_20160901_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Uploaded',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d')),
            ],
        ),
    ]
