# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 10:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0018_uploaded_vin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=128, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='safe',
            name='care_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Vin'),
        ),
    ]
