# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 10:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0019_auto_20160902_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded',
            name='files',
            field=models.FileField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
    ]
