# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 12:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0021_auto_20160902_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safe',
            name='files',
        ),
        migrations.AddField(
            model_name='safe',
            name='car_date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='car_price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pay.Safe'),
        ),
    ]
