# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0023_auto_20160902_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='fours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
