# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0024_clients_fours'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='check_status',
            field=models.IntegerField(default=1),
        ),
    ]
