# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 07:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0025_safe_check_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='install_status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='safe',
            name='sale_status',
            field=models.IntegerField(default=1),
        ),
    ]
