# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0026_auto_20160903_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='car_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
