# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-03 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0027_safe_car_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='pos_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
