# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-23 15:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0030_adviser'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clients',
            name='prov',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
