# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-11 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0033_auto_20160925_0956'),
    ]

    operations = [
        migrations.AddField(
            model_name='safe',
            name='b_care_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
