# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 14:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0035_auto_20161011_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploaded',
            old_name='vin',
            new_name='uid',
        ),
    ]
