# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0036_auto_20161019_1457'),
    ]

    operations = [
    ]
