# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-19 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0039_safe_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safe',
            name='client',
        ),
        migrations.AddField(
            model_name='safe',
            name='address',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='client_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='client_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='fours',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='identity_nu',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='identity_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='mobile',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='safe',
            name='prov',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
