# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-20 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0040_auto_20161019_1532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Firstproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_product', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Secondproduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('second_product', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
