# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-20 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pay', '0041_firstproduct_secondproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='safe',
            name='first_benefit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
